// 所有窗口数据
export const mockWindowsData = [
  {
    alwaysOnTop: false,
    focused: true,
    height: 632,
    id: 973095260,
    incognito: false,
    left: 0,
    state: "minimized",
    top: 480,
    type: "normal",
    width: 1204
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1128,
    id: 973095271,
    incognito: false,
    left: -8,
    state: "maximized",
    top: -8,
    type: "normal",
    width: 2064
  }
]

// 所有tab数据
export const mockTabsData = [
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://g.csdnimg.cn/static/logo/favicon32.ico",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095261,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "vue3源码详细分析_vue3源码解析_一花一world的博客-CSDN博客",
    url: "https://blog.csdn.net/ACCPluzhiqi/article/details/131146736",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://g.csdnimg.cn/static/logo/favicon32.ico",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973093261,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "vue3源码详细分析_vue3源码解析_一花一world的博客-CSDN博客",
    url: "https://blog.csdn.net/ACCPluzhiqi/article/details/131146736",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://g.csdnimg.cn/static/logo/favicon32.ico",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095262,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "Vite 完整版详解-CSDN博客",
    url: "https://blog.csdn.net/ACCPluzhiqi/article/details/132890858?spm=1001.2014.3001.5502",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://cloud.tencent.com/favicon.ico",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095263,
    incognito: false,
    index: 2,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "深度剖析Vite配置文件-腾讯云开发者社区-腾讯云",
    url: "https://cloud.tencent.com/developer/article/2301030",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "http://localhost:3000/favicon.ico",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095264,
    incognito: false,
    index: 3,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "深蓝保测评管理后台",
    url: "http://localhost:3000/bussinessLink",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://github.githubassets.com/favicons/favicon.svg",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095265,
    incognito: false,
    index: 4,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "core/packages/shared/src/normalizeProp.ts at main · vuejs/core",
    url: "https://github.com/vuejs/core/blob/main/packages/shared/src/normalizeProp.ts",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://developer.chrome.com/images/meta/favicon-32x32.png",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095266,
    incognito: false,
    index: 5,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "Manifest file format - Chrome for Developers",
    url: "https://developer.chrome.com/docs/extensions/mv3/manifest/",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://developer.chrome.com/images/meta/favicon-32x32.png",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095267,
    incognito: false,
    index: 6,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title:
      "Welcome to the Chrome Extension Manifest V3 - Chrome for Developers",
    url: "https://developer.chrome.com/docs/extensions/mv3/intro/",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://g.csdnimg.cn/static/logo/favicon32.ico",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095268,
    incognito: false,
    index: 7,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title:
      "#Chrome扩展程序开发教程--04：权限申请_chrome插件permissions-CSDN博客",
    url: "https://blog.csdn.net/qq_43519779/article/details/130307629",
    width: 1204,
    windowId: 973095260
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 632,
    highlighted: true,
    id: 973095269,
    incognito: false,
    index: 8,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: true,
    status: "unloaded",
    title: "插件 API | Vite 官方中文文档",
    url: "https://cn.vitejs.dev/guide/api-plugin.html",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      "https://gw.alipayobjects.com/zos/rmsportal/rlpTLlbMzTNYuZGGCVYM.png",
    groupId: -1,
    height: 632,
    highlighted: false,
    id: 973095270,
    incognito: false,
    index: 9,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "Ant Design of React - Ant Design",
    url: "https://ant-design.antgroup.com/docs/react/use-with-vite-cn",
    width: 1204,
    windowId: 973095260
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 844,
    highlighted: false,
    id: 973095272,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "vite-react",
    url: "http://127.0.0.1:5173/",
    width: 390,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://cloud.tencent.com/favicon.ico",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095273,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "React+vite引入antd并按需引入-腾讯云开发者社区-腾讯云",
    url: "https://cloud.tencent.com/developer/article/1992214",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      "https://gw.alipayobjects.com/zos/rmsportal/rlpTLlbMzTNYuZGGCVYM.png",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095274,
    incognito: false,
    index: 2,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "标签页 Tabs - Ant Design",
    url: "https://ant-design.antgroup.com/components/tabs-cn#tabs",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://www.tapd.cn/favicon.ico",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095276,
    incognito: false,
    index: 3,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title:
      "【待定】v2.39.16【保单管理】续保加保引导 -迭代-深蓝保小程序-TAPD平台",
    url: "https://www.tapd.cn/40331672/prong/iterations/card_view?q=08e5996de2682c4fc499a531a743f7af",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://www.tapd.cn/favicon.ico",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095277,
    incognito: false,
    index: 4,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "【保单管理】加保续保引导-深蓝保小程序-TAPD平台",
    url: "https://www.tapd.cn/40331672/prong/stories/view/1140331672001060678?url_cache_key=from_url_iteration_list_d6ceda75debc393cba1bd078690c9831&action_entry_type=stories",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://files.axshare.com/gsr/3741/images/favicon_play.ico",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095278,
    incognito: false,
    index: 5,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "编辑",
    url: "https://ule4vh.axshare.com/#id=lthms9&p=%E7%BC%96%E8%BE%91&g=1",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://developer.chrome.com/images/meta/favicon-32x32.png",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095279,
    incognito: false,
    index: 6,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "chrome.windows - Chrome for Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/windows/#method-getAll",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      "https://devpress.csdnimg.cn/6d9083c5866646dfb7c1896193dca26d.png",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095280,
    incognito: false,
    index: 7,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "chrome 插件开发指南_javascript_ 字节跳动技术团队-华为云开发者联盟",
    url: "https://huaweicloud.csdn.net/638f1379dacf622b8df8ec2e.html?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Eactivity-1-126113100-blog-130307629.235%5Ev38%5Epc_relevant_anti_vip_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Eactivity-1-126113100-blog-130307629.235%5Ev38%5Epc_relevant_anti_vip_base&utm_relevant_index=2",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095281,
    incognito: false,
    index: 8,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "基础能力 / 数据预拉取",
    url: "https://developers.weixin.qq.com/miniprogram/dev/framework/ability/pre-fetch.html",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095282,
    incognito: false,
    index: 9,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "重疾险 - Sketch MeaXure",
    url: "file://files.slbsz.com/%E6%96%87%E4%BB%B6%E5%85%B1%E4%BA%AB/%E8%AE%BE%E8%AE%A1/%E6%B7%B1%E8%93%9D%E4%BF%9D%E6%B5%8B%E8%AF%84%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E9%AB%98%E4%BF%9D%E7%9C%9F/%E9%A2%84%E7%BA%A6%E5%92%A8%E8%AF%A2%E9%A1%B5%E9%9D%A223.9.6/%E9%87%8D%E7%96%BE%E9%99%A9/index.html#s0",
    width: 2048,
    windowId: 973095271
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://cn.vitejs.dev/logo.svg",
    groupId: -1,
    height: 1003,
    highlighted: false,
    id: 973095287,
    incognito: false,
    index: 10,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "插件 API | Vite 官方中文文档",
    url: "https://cn.vitejs.dev/guide/api-plugin.html#universal-hooks",
    width: 2048,
    windowId: 973095271
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "",
    groupId: -1,
    height: 1003,
    highlighted: true,
    id: 973095292,
    incognito: false,
    index: 11,
    mutedInfo: {
      muted: false
    },
    pinned: false,
    selected: true,
    status: "complete",
    title: "扩展程序",
    url: "chrome://extensions/",
    width: 2048,
    windowId: 973095271
  }
]
